"use client";

import { useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import PublicPageShell from "@/components/layout/PublicPageShell";
import { MathExpression } from "@/components/math/MathExpression";
import { captureEvent } from "@/lib/analytics/posthog";

const sections: { id: string; title: string; keywords: string; content: ReactNode }[] = [
  { id: "getting-started", title: "Getting started", keywords: "add objects workspace math lab geometry studio", content: <><ol><li><Link href="/editor">Open the editor</Link>. Choose Math Lab for functions and fields, or Geometry Studio for geometric construction.</li><li>Open <strong>Objects</strong> and type in the blank equation input. Use <strong>+ Add</strong> for fields, parametric graphs, and geometric objects.</li><li>Edit its <strong>Definition</strong>. Select the object to see its controls in the <strong>Inspector</strong>.</li><li>Use the view controls to switch between <strong>2D</strong> and <strong>3D</strong>.</li></ol><p>On a phone, Objects and Inspector open as sheets. Close a sheet to return to the graph.</p><Link href="/examples" className="public-text-link">Start with a ready-made example →</Link></> },
  { id: "expressions", title: "Writing expressions", keywords: "formula input syntax power cosine sin math keyboard", content: <><p>Formula inputs are editable mathematical expressions. Use the keyboard button beside an input to open the math keyboard. Powers, fractions, and functions are typeset as you edit.</p><div className="guide-formula"><MathExpression expression="6*cos(x^2)^2" /></div><p>In the blank input, type a Cartesian equation without choosing its type. <MathExpression expression="x=y^2" /> and <MathExpression expression="x^2+y^2=4" /> create 2D curves; <MathExpression expression="x=y^2+z^2" /> creates a 3D surface. Bare <MathExpression expression="sin(x)" /> plots in 2D, while <MathExpression expression="sin(x)*cos(y)" /> plots a 3D scalar surface. Adding or removing z while editing automatically changes the graph and view. Press Enter to start another equation.</p><p>For an explicitly added surface, enter the right-hand side of the selected coordinate equation, such as <MathExpression expression="sin(x)*cos(y)" /> for <MathExpression expression="z = sin(x)*cos(y)" />. A parametric curve uses separate expressions for x, y, and z.</p><p>Use parentheses to make grouping explicit. Invalid expressions display a message near the definition; fix the expression to update the graph.</p></> },
  { id: "analyze", title: "Analyzing a graph", keywords: "gradient divergence curl laplacian differentiation hover tangent normal vector field", content: <><p>Select an object, open the Inspector, and choose <strong>Analyze</strong>. The available operations depend on the selected object.</p><ul><li><strong>Scalar surfaces:</strong> explore derivatives, gradients, and scalar visualizations.</li><li><strong>Vector fields:</strong> evaluate divergence, curl, field direction, and the vector Laplacian.</li><li><strong>Geometry:</strong> choose a compatible second object for distances, intersections, and other relations.</li></ul><p>For a gradient field, select a scalar surface and enable its gradient visualization. In 3D, the gradient arrows lie along the surface; in 2D, they show the field over its domain. A surface normal is a different operation.</p><p>When an operation asks for a point, activate its point picker and hover over the graph. The coordinate preview shows the point before you click to select it.</p></> },
  { id: "solve", title: "Solving fields", keywords: "proof solution steps complex cauchy riemann polar harmonic", content: <><p>Open <strong>Solve</strong> in Math Lab. Choose a scalar, vector, polar, or complex field and enter its definition. Supported results calculate automatically.</p><p>For curl, enter the vector components. You do not need to choose an evaluation point to get the symbolic result. Select <strong>Show solution</strong> to open the worked steps in an overlay.</p><p>Complex field analysis includes Cauchy–Riemann conditions, gradient, divergence, curl, and Laplacian. Polar analysis uses radial and angular components and states the domain restrictions in its solution.</p><p>Use <strong>Add to scene</strong> where available to plot the result. Solver drafts are not saved as project objects; added plots are.</p><aside className="guide-callout">An unsupported symbolic operation is reported explicitly. Complex logarithms and roots with branch choices are not automatically solved. Polar formulas involving division by the radius require a nonzero radius.</aside></> },
  { id: "measure", title: "Measuring and navigating", keywords: "distance angle coordinates pin orbit zoom pan", content: <><p>Use <strong>Distance</strong>, <strong>Angle</strong>, or <strong>Pin</strong> in the canvas toolbar, then pick the required points. Measurements appear on the graph and in Objects, where you can select or remove them.</p><p>Use the view controls to frame the scene or selected object. Drag to navigate, and use the scroll wheel or pinch gesture to zoom. The 2D and 3D views offer different navigation controls.</p><p>Use Undo and Redo in the editor to recover from scene edits. Object actions contains Remove; creation belongs in + Add.</p></> },
  { id: "save-share", title: "Saving, sharing, and exporting", keywords: "project local browser json png svg download import", content: <><p>Use the editor’s scene menu to save or open a local project. Local projects belong to this browser; clearing browser storage can remove them.</p><p>Use a share link to send a copy of a scene. A share link captures the scene at the time you create it. Later edits do not update that link.</p><p>For a portable backup, export JSON. Importing JSON uses the same scene validation as saved projects and shared scenes. Image exports are available from the editor’s export menu.</p><aside className="guide-callout">Large scenes can exceed the share-link size limit. Export JSON in that case.</aside></> },
  { id: "troubleshooting", title: "When something doesn’t work", keywords: "missing hidden error blank webgpu webgl help limits", content: <><dl><div><dt>Can’t find an object or a setting?</dt><dd>Open Objects, select the object, and open Inspector. On smaller screens these controls open sheets.</dd></div><div><dt>The graph is missing?</dt><dd>Check the object’s visibility, fix any definition error, and frame the scene. Check that the sampling domain includes the region you want.</dd></div><div><dt>An analysis control is unavailable?</dt><dd>Select an object of the required type. Some operations need a point or a compatible second object.</dd></div><div><dt>Rendering is slow?</dt><dd>Reduce sampling resolution or vector field density. The renderer uses WebGPU where available and can fall back to WebGL2.</dd></div></dl><p>Mathematical operations have supported-expression limits. Read the result’s domain and unsupported-operation messages before interpreting it.</p></> }
];

export default function DocumentationClientPage() {
  const [query, setQuery] = useState("");
  const matches = sections.filter((section) => `${section.title} ${section.keywords}`.toLowerCase().includes(query.trim().toLowerCase()));
  useEffect(() => { captureEvent("documentation_viewed"); }, []);
  return <PublicPageShell><div className="public-container guide-heading"><p className="public-eyebrow">Vinculum guide</p><h1>Find your way around.</h1><p className="public-lead">From your first expression to a worked solution.</p></div>
    <div className="public-container guide-layout"><aside className="guide-toc" aria-label="Guide contents"><label htmlFor="guide-search">Find a topic</label><input id="guide-search" type="search" placeholder="Try gradient or saving" value={query} onChange={(event) => setQuery(event.target.value)} /><nav aria-label="On this page">{matches.map(({ id, title }) => <a key={id} href={`#${id}`}>{title}</a>)}</nav>{matches.length === 0 && <p role="status">No topics match. <button type="button" onClick={() => setQuery("")}>Clear search</button></p>}</aside>
      <div className="guide-content">{sections.map(({ id, title, content }) => <section key={id} id={id}><h2>{title}</h2>{content}</section>)}</div>
    </div></PublicPageShell>;
}
