import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const process = Bun.spawn(["cargo", "build", "--locked", "--release", "--target", "wasm32-unknown-unknown", "-p", "vinculum-math-core"], { cwd: root, stdout: "inherit", stderr: "inherit" });
if (await process.exited !== 0) throw new Error("Rust/WASM build failed.");
const bytes = await readFile(resolve(root, "target/wasm32-unknown-unknown/release/vinculum_math_core.wasm"));
const destination = resolve(root, "apps/graph/lib/math/rustMathArtifact.ts");
await mkdir(resolve(root, "apps/graph/lib/math"), { recursive: true });
await writeFile(destination, `// Generated by bun run build:wasm. Do not edit.\nexport const RUST_MATH_WASM_BASE64 = ${JSON.stringify(bytes.toString("base64"))};\n`);
console.log(`Built Rust math core (${bytes.length} bytes).`);
